name = "osaka-kenpo"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# @cloudflare/next-on-pages用設定
pages_build_output_dir = ".vercel/output/static"

# D1データベース
[[d1_databases]]
binding = "DB"
database_name = "osaka-kenpo-db"
database_id = "c2e526ac-8b9a-41c1-933a-e31c60490462"
